---
- name: Deploy GithubBranchesApp service
  hosts: qa
  become: true

  tasks:
    - name: Stop GithubBranchesApp Service
      service:
        name: GithubBranchesApp
        state: stopped

    - name: Remove existing GithubBranchesApp folder
      command: chdir=/home/naptadminvm1 rm -rf GithubBranchesApp-qa

    - name: Extract GithubBranchesApp.tgz
      ansible.builtin.unarchive:
        src: /var/lib/jenkins/workspace/GithubBranchesApp-qa.tgz
        dest: /home/naptadminvm1

    - name: Run mvn clean install
      command: chdir=/home/naptadminvm1/GithubBranchesApp-qa mvn clean install

    - name: Start GithubBranchesApp Service
      service:
        name: GithubBranchesApp
        state: started
